options:
  app_name:
    type: string
    default: myapp
    description: Application Name
  app_port:
    type: string
    default: 8000
    description: Port where the application will handle requests
  app_scm:
    type: string
    default: git
    description: Repository type (git/bzr/...)
  app_url:
    type: string
    default: "http://github.com/mmm/testnode.git"
    description: Application repository URL
  app_branch:
    type: string
    default: master
    description: Application repository deployment branch
  install_root:
    type: string
    default: /opt
    description: Install the application in app_name under this directory
  app_user:
    type: string
    default: ubuntu
    description: run-as user
