#!/bin/bash

set -eu # -x for verbose logging to juju debug-log

umask 002

install_root=`config-get install_root`
app_name=`config-get app_name`
app_dir="$install_root/$app_name"
app_branch=`config-get app_branch`

cd $app_dir

# Always fetch latest if branch requested
if git checkout origin/${app_branch}; then # is a local branch
  git fetch origin && git checkout origin/${app_branch}
else # tag/commit ref?
  if ! git checkout ${app_branch}; then # commit does not exist locally
    git fetch origin
    if ! git checkout origin/${app_branch}; then # not a new remote branch, is a commit ref/tag
	git checkout $app_branch
    fi
  fi
fi

npm update && npm install

chown -Rf ${app_user}.${app_user} ${app_dir}

service ${app_name} restart
